---

- hosts: ec2instance
  sudo: true
  vars:
   destination: "/tmp/tomcatworkspace"
   dockername: "sctomcat"

  tasks:
   - name: Check if container exist
     shell: "docker ps -a | grep {{ dockername }}"
     register: docker_res
     ignore_errors: true

#   - debug:
#       var: docker_res

   - name: destroy current container if exist
     shell: "docker rm -f {{ dockername }}"
     when: docker_res|succeeded

   - name: delete destination workspace
     shell: "rm -rf {{ destination }}"

   - name: copy workspace
     shell: "docker cp jenkins-slave:{{ workspace }}/. {{ destination }}"

   - name: build docker image
     command: "docker build -t {{ dockername }}:{{ buildid }} {{ destination }}"

   - name: docker run
     shell: "docker run --name {{ dockername }}  -d -p 8082:8082 {{ dockername }}:{{ buildid }}"

